### ISSUE TITLE
Need a file or database for persistent storage

### ISSUE THREAD

**Issue by amberdaniels** [faithlighttech/DanielsFinalProject#14]
Someone just asked if they should do a file for the given information, but Dr Gang suggested a database. However that is beyond our scope of learning for this class. What do you think?

**Comment by docrinehart** [comment]
There are many simple implementations of database or file storage, and while not expressly stated as  requirement, is necessary to keep data long-term instead of just for a single session. My intent was that we'll be setting up a basic EF implementation and use Roundhouse to manage the migration scripts.

**Comment by docrinehart** [comment]
Note @amberdaniels you can refer to someone in a comment by using the '@' symbol.

**Comment by amberdaniels** [comment]
ok @docrinehart  :)
